### ISSUE TITLE
Don't Include Binaries

### ISSUE THREAD

**Issue by jamescarr** [mmckeen/packer-package#1]
Thanks for putting this together but I think one improvement you could make for others to use this is to remove the packer binaries and have the build script pull down packer as part of the build process.

**Comment by mmckeen** [comment]
Thanks for the feedback.  I'm actually going to move the binaries to git-lfs.  My main concern with pulling the binaries on build is that they won't be easily tracked in version control.  Using git-lfs should easily fix this while reducing the size of the repository.
